# Generated by Django 5.2.17 on 2026-08-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
